pr:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app 

pool:
  vmImage: ubuntu-latest

steps:
- bash: 
    npm install sfdx-cli --global
  displayName: "Salesforce sfdx cli installer"

- bash: 
    touch access.key
  displayName: "Temp file for auth url file creation"

- bash:    
    echo $SF_URL > access.key
  env:
    SF_URL: $(SalesforceAuthUrl)
  displayName: "Write url to the temp file"

- bash: 
    sfdx force:auth:sfdxurl:store -f "access.key" -a salesforce.org
  displayName: "Connect to the Salesforce org"

- bash: 
    sfdx force:org:display -u org.org
  displayName: "Salesforce org connection doublecheck"