pr:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app 

pool:
  ##vmImage: ubuntu-latest
  ##name: default
  name: Azure Pipelines
  vmImage: ubuntu-latest
  
steps:
- task: UseNode@1
# - taks: Npm@1
#     inputs: 
#       command: 'install'


- task: Npm@1
  inputs:
#     command: 'install'
    # customCommand: install sfdx-cli --global
    command: custom
    customCommand: install sfdx-cli --global

# - bash: 
#     npm install sfdx-cli --global
#   displayName: "Salesforce sfdx cli installer"

- bash: 
    touch access.key
  displayName: "Temp file for auth url file creation"

- bash:    
    echo $SF_URL > access.key
  env:
    SF_URL: $(SalesforceAuthUrl)
  displayName: "Write url to the temp file"

- bash: 
    sfdx force:auth:sfdxurl:store -f "access.key" -a salesforce.org
  displayName: "Connect to the Salesforce org"

- bash: 
    sfdx force:org:display -u salesforce.org
  displayName: "Salesforce org connection doublecheck"

- bash: 
    echo $TEST
  env:
    TEST: $(test)
  displayName: "Variables test" 