
pr: ## allows only pull requests to trigger the pipeline
  branches: ## the following branches will be included
      include:
      - '*'
  paths:
     include:
     ## the following files or folders will be included
     - force-app 

pool:
  ## a Linux virtual machine will be used
  vmImage: ubuntu-latest

steps:
- bash: 
    npm install sfdx-cli --global
  displayName: "Salesforce sfdx cli installer"

- bash: 
    touch test.key
  displayName: "Temp file for auth url file creation"

- bash:    
    echo $TEST_SURFF > test.key ##include url to the temp file
  env:
  ##extraction of env variable
    TEST_SURFF: $(test)
  displayName: "Write url to the temp file"

- bash: 
    sfdx force:auth:sfdxurl:store -f "test.key" -a org.org
  displayName: "Connect to the Salesforce org"

- bash: 
    sfdx force:org:display -u org.org
  displayName: "Salesforce org connection doublecheck"