# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
      include:
      - master
  paths:
     exclude:
     - config
     - README.md
     - .gitignore
     - .project
     - .salesforcedx.yaml
     - LICENSE
     - orgacc.key
     - sfdx-project.json 

pool:
  vmImage: ubuntu-latest

steps:
- bash: 
    ##echo "this is the version os cli" 
    ##npm sfdx-cli --version
    npm install sfdx-cli --global
    ##sfdx force:auth:sfdxurl:store -f orgacc.key
    ##npm sfdx-cli force:source:deploy -p /force-app

- bash: 
    ##cat > org.link
    touch test.key
    
- bash:    
    echo $TEST_SURFF > test.key
  env:
    ##MY_MAPPED_ENV_VAR_02: $(SalesforceOrgAuthUrl)
    TEST_SURFF: $(test)

- bash: 
    sfdx force:auth:sfdxurl:store -f "test.key" -a org.org
- bash: 
    sfdx force:org:display -u org.org
  displayName: "Last Bash Naming test"


 ##- bash:
##    echo $MY_MAPPED_ENV_VAR
 ##    echo $TEST_SURFF
 ##  env:
##    MY_MAPPED_ENV_VAR: $(SalesforceOrgAuthUrl)
 ##    TEST_SURFF: $(test)