# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
 branches:
     include:
     - master
 paths:
     exclude:
     - config
     - README.md
     - .gitignore
     - .project
     - .salesforcedx.yaml
     - LICENSE
     - orgacc.key
     - sfdx-project.json 

pool:
  vmImage: ubuntu-latest

steps:


##- bash: 
    ##echo "this is the version os cli" 
    ##npm sfdx-cli --version
    ##npm install sfdx-cli --global
    ##sfdx force:auth:sfdxurl:store -f orgacc.key
    ##npm sfdx-cli force:source:deploy -p /force-app

##- bash: 
##    sfdx force:auth:sfdxurl:store -f orgacc.key

- bash:
    echo %(test)